modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="something"
version="1.0.0"
displayName="SOMETHING"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="TrainingGR01, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.something]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.something]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration